# Generated by Django 3.0.5 on 2020-05-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
