# Generated by Django 3.0.5 on 2020-07-07 10:36

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attrs',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
